problems: {}

penalties:
  guven:
    penalty_weight: 100.0

  wang:
    penalty_weight: 50.0

  reverse_guven:
    penalty_weight: 100.0

solvers:
  projected_gradient_descent:
    step_size: 0.03
    max_iterations: 100
    objective_tolerance: null

  slsqp:
    max_iterations: 100
    ftol: 1.0e-6

  trust_constr:
    max_iterations: 250
    gtol: 1.0e-4
    xtol: 1.0e-4
    barrier_tol: 1.0e-4

  linprog_highs: {}
